<div class="grid grid-cols-1 md:grid-cols-2 gap-5">
    <div><label class="block text-sm font-bold text-primary-900 mb-2">اسم الطبيب <span class="text-red-500">*</span></label><input name="name" value="{{ old('name', $doctor->user->name ?? '') }}" class="input-field" required></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">البريد الإلكتروني <span class="text-red-500">*</span></label><input type="email" name="email" value="{{ old('email', $doctor->user->email ?? '') }}" class="input-field" required></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">القسم <span class="text-red-500">*</span></label><select name="department_id" class="select-field" required><option value="">اختر القسم</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $doctor->department_id ?? '') == $department->id)>{{ $department->name }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">التخصص <span class="text-red-500">*</span></label><input name="specialization" value="{{ old('specialization', $doctor->specialization ?? '') }}" class="input-field" required></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">رقم الهاتف</label><input name="phone" value="{{ old('phone', $doctor->phone ?? '') }}" class="input-field"></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">الراتب</label><input type="number" min="0" step="0.01" name="salary" value="{{ old('salary', $doctor->salary ?? '') }}" class="input-field"></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">كلمة المرور @isset($doctor)<span class="text-xs text-neutral-400 font-normal">(اختياري للتغيير)</span>@else<span class="text-red-500">*</span>@endisset</label><input type="password" name="password" class="input-field" autocomplete="new-password" {{ isset($doctor) ? '' : 'required' }}></div>
    <div><label class="block text-sm font-bold text-primary-900 mb-2">تأكيد كلمة المرور @if(!isset($doctor))<span class="text-red-500">*</span>@endif</label><input type="password" name="password_confirmation" class="input-field" autocomplete="new-password" {{ isset($doctor) ? '' : 'required' }}></div>
</div>
